name: Deploy Vue App

on:
  push:
    branches:
      - main  # Деплой с ветки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: Frontend  # Переключаемся в папку Frontend

      - name: Build project
        run: npm run build
        working-directory: Frontend  # Билдим в папке Frontend

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./Frontend/dist  # Указываем путь к папке сборки
